const products = [
    {
        _id: '1',
        name: 'Citrozaik',
        image: 'https://media2.3bir.rs/2019/07/CITROZAIK-600x450.png',
        description:
            'Osvezavajuca IPA iz 3Bir pivare sa citrusnim aromama, izrazenim hmeljem i pitkim zavrsetkom.',
        category: 'IPA',
        style: 'India Pale Ale',
        strength: '5.5%',
        taste: 'Citrusno, hmeljno, osvezavajuce',
        price: 340.00,
        countInStock: 48,
        rating: 4.7,
        numReviews: 31,
    },
    {
        _id: '2',
        name: 'Arhipelag',
        image: 'https://media2.3bir.rs/2019/07/ARHIPELAG-600x450.png',
        description:
            'American IPA punog hmeljnog karaktera, sa vocnim mirisom i jasnom gorcinom za ljubitelje intenzivnijeg craft ukusa.',
        category: 'IPA',
        style: 'American IPA',
        strength: '6.2%',
        taste: 'Tropsko, hmeljno, gorkasto',
        price: 360.00,
        countInStock: 32,
        rating: 4.9,
        numReviews: 44,
    },
    {
        _id: '3',
        name: 'Barbados',
        image: 'https://media2.3bir.rs/2019/06/BARBADOS-600x450.png',
        description:
            'Witbier laganog tela, psenicnog karaktera i neznih zacinjenih nota. Dobar izbor za tople dane i laganu hranu.',
        category: 'Psenicno',
        style: 'Witbier',
        strength: '5.0%',
        taste: 'Psenicno, vocno, blago zacinjeno',
        price: 320.00,
        countInStock: 21,
        rating: 4.8,
        numReviews: 27,
    },
    {
        _id: '4',
        name: 'Shake!',
        image: 'https://media2.3bir.rs/2019/02/SHAKE-2-600x450.png',
        description:
            'Milk Stout sa kremastim telom, tamnim sladovima i desertnim karakterom. Namenjen za sporije ispijanje i puniji ukus.',
        category: 'Stout',
        style: 'Milk Stout',
        strength: '5.0%',
        taste: 'Kremasto, tamno, slatkasto',
        price: 380.00,
        countInStock: 37,
        rating: 4.6,
        numReviews: 19,
    },
    {
        _id: '5',
        name: 'Akira',
        image: 'https://media2.3bir.rs/2018/07/AKIRA-600x450.png',
        description:
            'Red IPA sa aromama manga i tropskog voca, uravnotezena izmedju sladnog tela i hmeljne gorcine.',
        category: 'IPA',
        style: 'Red IPA',
        strength: '6.5%',
        taste: 'Mango, tropsko voce, hmeljno',
        price: 390.00,
        countInStock: 18,
        rating: 4.5,
        numReviews: 16,
    },
    {
        _id: '6',
        name: 'Hopacabana',
        image: 'https://media2.3bir.rs/2018/05/HOPACABANA-600x450.png',
        description:
            'Blonde Ale iz 3Bir ponude, laganije telo, svetliji sladni profil i prijatan hmeljni zavrsetak.',
        category: 'Ale',
        style: 'Blonde Ale',
        strength: '4.8%',
        taste: 'Svetlo, pitko, blago hmeljno',
        price: 310.00,
        countInStock: 54,
        rating: 4.4,
        numReviews: 12,
    },
];

export default products;
